export const commissionCategory = {
  Jewellery: 20,
  'Automation & Robotics': 10,
  'Automotive Accessories': 20,
  'Beauty & Grooming': 6,
  'Baby Care': 6,
  Books: 5,
  'Music, Movie & Posters': 5,
  'Camera & Accessories': 12,
  'Home & Kitchen': 5,
  'Kitchen, Cookware & Serveware': 5,
  'Clothing & Accessories': 15,
  Computers: 20,
  Gaming: 5,
  Eyewear: 10,
  Sunglasses: 10,
  'Food Products': 3,
  Footwear: 13,
  Furniture: 12,
  'Health & Personal Care Appliances': 5.5,
  'Home Decor': 15,
  'Home Furnishing': 10,
  'Home Improvement': 10,
  'Home, Cleaning & Bathroom Accessories': 3,
  'Kitchen, Cookware & Serveware': 10,
  'Bags, Wallets & Belts': 3,
  'Mobile & Accessories': 3,
  'Musical Instruments': 8,
  'Pens & Stationary': 15,
  'Pet Supplies': 10,
  'Exercise & Fitness': 11,
  'Toys & Games': 10,
  Watches: 15,
  'Wearable Smart Devices': 15,
};

export const fixedFeeTable = {
  300: 13,
  500: 11,
  1000: 24,
};
